services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - JWT_SECRET=VENDERGAS
      - MONGO_URI=mongodb://mongodb:27017/desafio-db
    depends_on:
      - mongodb
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
volumes:
  mongo-data:
