version: '3.8'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - JWT_SECRET=VENDERGAS
      - MONGO_URI=mongodb://mongodb:27017/desafio-db
    depends_on:
      - mongo
    volumes:
      - .:/app
    restart: always

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
